lang-list-flores-200-dev.md:
	echo "     lines  words path" > lang-list-flores-200-dev.md
	wc -lw flores-200-dev/* >> lang-list-flores-200-dev.md

lang-list-flores-200-devtest.md:
	echo "    lines   words path" > lang-list-flores-200-devtest.md
	wc -lw flores-200-devtest/* >> lang-list-flores-200-devtest.md

lang-list-multitext-nllb-seed.md:
	echo "    lines  words  path" > lang-list-multitext-nllb-seed.md
	wc -lw multitext-nllb-seed/* >> lang-list-multitext-nllb-seed.md

lang-list: \
	lang-list-flores-200-dev.md \
	lang-list-flores-200-devtest.md \
	lang-list-multitext-nllb-seed.md


# multitext-nllb-seed-edits/
# flores-200-dev-edits/
# flores-200-devtest-edits/